src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"Titre"})
     */
    private $Slug;
    /**
     * @ORM\Column(type="text")
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     * @Gedmo\Timestampable(on="create")
     */
    private $Published;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

  /*  public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }
*/
    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getPublished(): ?\DateTimeInterface
    {
        return $this->Published;
    }
/*
    public function setPublished(\DateTimeInterface $Published): self
    {
        $this->Published = $Published;

        return $this;
    }

    */
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
    <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
		<meta name="description" content=""/>
		<meta name="Malak" content=""/>
		<title>	Blog Symfony</title>
        <!-- stylesheet link-->
		<link rel="stylesheet" href="{{asset('assets/theme/css/styles.css')}}"> 
        {% block stylesheets %}{% endblock %}

    </head>
    <body id="page-top">
			<!-- Navigation-->
			<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
				<div class="container">
					<a class="navbar-brand js-scroll-trigger" href="{{path('blog')}}"><img src="{{asset('assets/theme/assets/img/navbar-logo.svg')}}" alt=""/></a>

					<div class="collapse navbar-collapse" id="navbarResponsive">
						<ul class="navbar-nav text-uppercase ml-auto">
							{% if  app.user and 'ROLE_ADMIN' in app.user.roles %}
							<li class="nav-item">
								<a class="nav-link js-scroll-trigger" href="{{ path('blog_create') }}">Créer Article</a>
							</li>
							{% endif %}
							<li class="nav-item">
								<a class="nav-link js-scroll-trigger" href="{{path('api')}}">Notre API</a>
							</li>
							<li class="nav-item">
								<a class="nav-link js-scroll-trigger" href="{{path('api_used')}}">Articles API Externe </a>
							</li>
							{% if  app.user and 'ROLE_ADMIN' in app.user.roles %}
							<li class="nav-item">
								<a class="nav-link js-scroll-trigger" href="{{path('app_logout')}}">Déconnexion</a>
							</li>
							
							{% else %}
							<li class="nav-item">
								<a class="nav-link js-scroll-trigger" href="{{path('app_login')}}">Connexion</a>
							</li>
							{% endif %}
						</ul>
					</div>
				</div>
			</nav>

			<!-- Bootstrap core JS-->

			<!-- Masthead-->
			<header class="masthead">
				<div class="container">
					<div class="masthead-subheading">Bienvenue à Notre Blog!</div>
					<div class="masthead-heading text-uppercase">Faux Articles ^_^</div>
				</div>
			</header>

			

			<div class="container"> {%  block body %}{% endblock %}


				</div>
				<!-- Bootstrap core JS-->
				<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
				<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
				<!-- Third party plugin JS-->
				<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
				<!-- Contact form JS-->
				<script src="{{asset('assets/theme/assets/mail/jqBootstrapValidation.js')}}"></script>
				<script src="{{asset('assets/theme/assets/mail/contact_me.js')}}"></script>
				<!-- Core theme JS-->
				<script src="{{asset('assets/theme/js/scripts.js')}}"></script>
				{% block javascripts %}{% endblock %}


    </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<div class="text-center">
		<h2 class="section-heading text-uppercase">
			Articles
		</h2>
	</div>

	<div class="container">

		{% for article in articles  %}

			<div class="article">
				<h2>{{article.titre}}</h2>
				<h3 class="section-subheading text-muted">{{article.slug}}</h3>
				<div class="metadata">
					publié le
					{{article.published | date('d/m/y')}}
				</div>
				<div class="content">
					<p class="text-muted">
						{{article.content| raw }}
					</p>
					<a href="{{path('blog_show', {'id': article.id})}}" class="btn btn-primary">
						Visualiser
					</a>
					{% if app.user and 'ROLE_ADMIN' in app.user.roles  %}
						<a href="{{path('blog_Edit', {'id': article.id})}}" class="btn btn-success">
							Modifier
						</a>
						<a href="{{path('blog_Delete', {'id': article.id})}}" class="btn btn-danger">
							Supprimer
						</a>
					{% endif %}
				</div>

			</div>

		{% endfor %}
	</div>

{% endblock %}